### PR TITLE
Update csp.go

### PR DESCRIPTION
**Pull request by jaikishantulswani**
Fetching domains from `Content-Security-Portal` header and also strip `*.` from results.

### CODE REVIEW

**Comment by edoardottt** [comment]
Hi @jaikishantulswani ! Thanks for your contribution. 
I cannot find a reference for `Content-Security-Portal`. Can you explain a lil bit what's that?

**Comment by jaikishantulswani** [comment]
> Hi @jaikishantulswani ! Thanks for your contribution. I cannot find a reference for `Content-Security-Portal`. Can you explain a lil bit what's that?

Hi @edoardottt thanks for your response on this. While testing some private bug bounty programs I have found this header in the response that contains the other domains associated with the program, thats why I added this.

**Comment by edoardottt** [comment]
I cannot find any reference online for this header. I suspect this is a custom header used only in that program.

**Comment by kleozzy** [comment]
It doesnt hurt to have this anyway , if its there fetch it.

**Pull request closed without merging**
